### ISSUE TITLE
Sucessul Login by E-mail to Admin

### ISSUE THREAD

**Issue by espellcaste** [buddydev/wp-user-login-notifier#2]
No need for the admin to know if a user logged in the website. Imagine 10 or 100k users in a website with a few % logging in. It'll be pretty hard on the admin to keep track of that.

Maybe one could set a custom email just to keep a record for some reason, that's just the scenario I can see this being applied and even that, for me, I'd find another way.

So I'd remove it!

**Comment by sbrajesh** [comment]
Hi @espellcaste 
Thank you for the details.
You can disable this setting from Dashboard->Settings->Wp User Login Notifier settings page. It is already there to turn of all of these settings.

**Comment by espellcaste** [comment]
Ops, sorry! That's true! I was looking at the code and saw the function there and didn't thought about the options.
